### ISSUE TITLE
Can't change the minSize dynamically

### ISSUE THREAD

**Issue by ilyasmez** [runjuu/column-resizer#4]
Thank you for your work!

I'm enjoying this library, but I faced one weird issue:
The `minSize` (and potentially `maxSize` as well) can't be changed dynamically.

Here is Codesandbox with an example:
https://codesandbox.io/s/column-resizer-dynamic-minsize-jllyxy?file=/src/App.js

And here is demo video:

https://github.com/runjuu/column-resizer/assets/30146019/bf557725-4617-46cd-998d-c7f99a2345bc

### Current behavior
The minSize of the section is not updated (set to `undefined`) when the checkbox is unchecked.
And the section can't be resized to width below the initial minSize.

### Expected behavior
After unchecking the checkbox, I should be able to resize the section to a width as low as 0px.

### Notes
This issue happens only when setting the minSize dynamically to a value lower than the initial one (minSize<150 or undefined, in the example above). But setting a higher value (minSize>150) seems to work.

**Comment by runjuu** [comment]
Hi @ilyasmez, thanks for the detailed report, and sorry for the late response (I don’t know why GitHub didn’t send an email to notify me). This issue should be fixed in the newly released version. Update @column-resizer/react to 1.2.3 and everything should now work as expected.

**Comment by ilyasmez** [comment]
Thank you very much for the quick fix @runjuu! now everything is working as expected indeed! 👏
